routes/web.php
<?php

use App\Tools\MemberRegistration;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/en/home');
});

//Route::get('/en/home', function () { return view('index');});
Route::get('/en/home', ['uses' =>'HomeController@index']);
Route::get('/en/{slug}', ['uses' =>'ContentController@page']);
Route::get('/display/{key}', ['uses' =>'SuggestionController@display']);
Route::get('/view/{slug}', ['uses' =>'SuggestionController@view']);
Route::get('/member/points', ['uses' =>'MemberController@checkPoints']);
Route::get('/serena-hotels/points', ['uses' =>'PrestigeCardHotelController@find']);

Route::get('/menu-items/{menu_id}/create', ['uses' =>'MenuItemController@create']);
Route::get('/menu-items/{menu_id}', ['uses' =>'MenuItemController@index']);
Route::get('/suggestions/{type_id}/create', ['uses' =>'SuggestionController@create']);
Route::get('/suggestions/{type_id}', ['uses' =>'SuggestionController@index']);
Route::get('/prestige-card-hotels/find', ['uses' =>'PrestigeCardHotelController@find']);	
Route::get('/prestige-card-points/{hotel_id}/create', ['uses' =>'PrestigeCardPointController@create']);
Route::get('/prestige-card-points/{hotel_id}', ['uses' =>'PrestigeCardPointController@index']);
Route::get('/prestige-card-meal-points/{hotel_id}/create', ['uses' =>'PrestigeCardMealPointController@create']);
Route::get('/prestige-card-meal-points/{hotel_id}', ['uses' =>'PrestigeCardMealPointController@index']);

Route::get('/members/enrol', ['uses' =>'MemberController@enrol']);

Route::get('/confirm/success', function () { 
	return redirect('/confirm')->with('success', 'Member has been successfully enrolled');
});
Route::get('/confirm/error', function () { 
	return redirect('/confirm')->with('error', 'Member not enrolled, an error occured!');
});

Route::get('/confirm', function () { return view('members.confirm');});

Route::get('/points2', function () { return view('members.points');});

Route::resource('prestige-card-hotels', 'PrestigeCardHotelController');
Route::resource('prestige-card-points', 'PrestigeCardPointController');
Route::resource('prestige-card-meal-points', 'PrestigeCardMealPointController');
Route::resource('menu-items', 'MenuItemController');
Route::resource('menus', 'MenuController');
Route::resource('suggestions', 'SuggestionController');
Route::resource('suggestion-types', 'SuggestionTypeController');
Route::resource('content-types', 'ContentTypeController');
Route::resource('contents', 'ContentController');
Route::resource('countries', 'CountryController');
Route::resource('members', 'MemberController');
Route::resource('admin/members', 'MemberController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin');

app/PrestigeCardPoint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PrestigeCardPoint extends Model
{
    protected $fillable = [
        'hotel_id',
        'room_type',
        'points',
        'low_season_points',
        'mid_season_points',
        'high_season_points',
        'peak_season_points',
        'upgrade_points',
        'remarks'
    ];
}

app/Http/Controllers/PrestigeCardPointController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PrestigeCardPoint;

class PrestigeCardPointController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($hotel_id)
    {
        $prestigeCardPoints = PrestigeCardPoint::where('hotel_id',$hotel_id)->get();
        return view('prestige_card_points.index', compact('prestigeCardPoints'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($hotel_id)
    {
        $prestigeCardPoint = new PrestigeCardPoint();
        $prestigeCardPoint->hotel_id = $hotel_id;
        return view('prestige_card_points.create', compact('prestigeCardPoint'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'hotel_id' => 'required|integer',
            'room_type' => 'required',
            'remarks' => 'required'
        ]);
        $prestigeCardPoint = new PrestigeCardPoint([
            'hotel_id' => $request->get('hotel_id'),
            'room_type' => $request->get('room_type'),
            'points' => 0,
            'low_season_points' => $request->get('low_season_points'),
            'mid_season_points' => $request->get('mid_season_points'),
            'high_season_points' => $request->get('high_season_points'),
            'peak_season_points' => $request->get('peak_season_points'),
            'upgrade_points' => $request->get('upgrade_points'),
            'remarks' => $request->get('remarks')
        ]);
        $prestigeCardPoint->save();
        return redirect('/prestige-card-points/' . $request->get('hotel_id'))->with('success', 'Points entry has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $prestigeCardPoint = PrestigeCardPoint::find($id);
        return view('prestige_card_points.edit', compact('prestigeCardPoint'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'hotel_id' => 'required|integer',
            'room_type' => 'required',
            'remarks' => 'required'
        ]);
        $prestigeCardPoint = PrestigeCardPoint::find($id);
        $prestigeCardPoint->hotel_id = $request->get('hotel_id');
        $prestigeCardPoint->room_type = $request->get('room_type');
        $prestigeCardPoint->low_season_points = $request->get('low_season_points');
        $prestigeCardPoint->mid_season_points = $request->get('mid_season_points');
        $prestigeCardPoint->high_season_points = $request->get('high_season_points');
        $prestigeCardPoint->peak_season_points = $request->get('peak_season_points');
        $prestigeCardPoint->upgrade_points = $request->get('upgrade_points');
        $prestigeCardPoint->remarks = $request->get('remarks');
        $prestigeCardPoint->save();
        return redirect('/prestige-card-points/' . $request->get('hotel_id'))->with('success', 'Points entry has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/prestige_card_points/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Points Entry Item
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('prestige-card-points.store') }}">
          @include('prestige_card_points.form')
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/prestige_card_points/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Points Entry Item
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('prestige-card-points.update', $prestigeCardPoint->id) }}">
        @method('PATCH')
        @csrf
        @include('prestige_card_points.form')
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/prestige_card_points/form.blade.php
<div class="form-group">
  @csrf
  <label for="name">Room Type:</label>
  <input type="text" class="form-control" name="room_type" value={{ $prestigeCardPoint->room_type }}></input>
</div>
<div class="form-group">
  <label for="name">Low Season:</label>
  <input type="text" class="form-control" name="low_season_points" value={{ $prestigeCardPoint->low_season_points }}></input>
</div>
<div class="form-group">
  <label for="name">Mid Season:</label>
  <input type="text" class="form-control" name="mid_season_points" value={{ $prestigeCardPoint->mid_season_points }}></input>
</div>
<div class="form-group">
  <label for="name">High Season:</label>
  <input type="text" class="form-control" name="high_season_points" value={{ $prestigeCardPoint->high_season_points }}></input>
</div>
<div class="form-group">
  <label for="name">Peak Season:</label>
  <input type="text" class="form-control" name="peak_season_points" value={{ $prestigeCardPoint->peak_season_points }}></input>
</div>
<div class="form-group">
  <label for="name">Upgrade Points:</label>
  <input type="text" class="form-control" name="upgrade_points" value={{ $prestigeCardPoint->upgrade_points }}></input>
</div>
<div class="form-group">
  <label for="name">Remarks:</label>
  <input type="text" class="form-control" name="remarks" value={{ $prestigeCardPoint->remarks }}></input>
</div>
<input type="hidden" name="hotel_id" value={{ $prestigeCardPoint->hotel_id }}></input>

resources/views/prestige_card_points/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <a href="{{$prestigeCardPoints[0]->hotel_id}}/create" class="btn btn-primary">Add Item</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Room Type</td>
          <td>Points</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($prestigeCardPoints as $prestigeCardPoint)
        <tr>
            <td>{{$prestigeCardPoint->id}}</td>
            <td>{{$prestigeCardPoint->room_type}}</td>
            <td>{{$prestigeCardPoint->points}}</td>
            <td><a href="{{ route('prestige-card-points.edit',$prestigeCardPoint->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('prestige-card-points.destroy', $prestigeCardPoint->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection