routes/web.php
<?php

use App\Tools\MemberRegistration;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/en/home');
});

//Route::get('/en/home', function () { return view('index');});
Route::get('/en/home', ['uses' =>'HomeController@index']);
Route::get('/en/{slug}', ['uses' =>'ContentController@page']);
Route::get('/display/{key}', ['uses' =>'SuggestionController@display']);
Route::get('/view/{slug}', ['uses' =>'SuggestionController@view']);
Route::get('/member/points', ['uses' =>'MemberController@checkPoints']);
Route::get('/serena-hotels/points', ['uses' =>'PrestigeCardHotelController@find']);

Route::get('/menu-items/{menu_id}/create', ['uses' =>'MenuItemController@create']);
Route::get('/menu-items/{menu_id}', ['uses' =>'MenuItemController@index']);
Route::get('/suggestions/{type_id}/create', ['uses' =>'SuggestionController@create']);
Route::get('/suggestions/{type_id}', ['uses' =>'SuggestionController@index']);
Route::get('/prestige-card-hotels/find', ['uses' =>'PrestigeCardHotelController@find']);	
Route::get('/prestige-card-points/{hotel_id}/create', ['uses' =>'PrestigeCardPointController@create']);
Route::get('/prestige-card-points/{hotel_id}', ['uses' =>'PrestigeCardPointController@index']);
Route::get('/prestige-card-meal-points/{hotel_id}/create', ['uses' =>'PrestigeCardMealPointController@create']);
Route::get('/prestige-card-meal-points/{hotel_id}', ['uses' =>'PrestigeCardMealPointController@index']);

Route::get('/members/enrol', ['uses' =>'MemberController@enrol']);

Route::get('/confirm/success', function () { 
	return redirect('/confirm')->with('success', 'Member has been successfully enrolled');
});
Route::get('/confirm/error', function () { 
	return redirect('/confirm')->with('error', 'Member not enrolled, an error occured!');
});

Route::get('/confirm', function () { return view('members.confirm');});

Route::get('/points2', function () { return view('members.points');});

Route::resource('prestige-card-hotels', 'PrestigeCardHotelController');
Route::resource('prestige-card-points', 'PrestigeCardPointController');
Route::resource('prestige-card-meal-points', 'PrestigeCardMealPointController');
Route::resource('menu-items', 'MenuItemController');
Route::resource('menus', 'MenuController');
Route::resource('suggestions', 'SuggestionController');
Route::resource('suggestion-types', 'SuggestionTypeController');
Route::resource('content-types', 'ContentTypeController');
Route::resource('contents', 'ContentController');
Route::resource('countries', 'CountryController');
Route::resource('members', 'MemberController');
Route::resource('admin/members', 'MemberController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin');

app/PrestigeCardHotel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PrestigeCardHotel extends Model
{
    protected $fillable = [
        'hotel_name',
        'country_id',
        'mode',
        'remarks'
    ];
}

app/Http/Controllers/PrestigeCardHotelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\PrestigeCardHotel;
use App\Country;
use Image;

class PrestigeCardHotelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $prestigeCardHotels = PrestigeCardHotel::all();
        return view('prestige_card_hotels.index', compact('prestigeCardHotels'));
    }


public function show(Request $request) {
    $countryName = $request->get('country');
    $hotelName = $request->get('hotel');
    $countryList1 = DB::table('countries')->select('country_name')->get();
    $hotelList1 = DB::table('prestige_card_hotels')->select('hotel_name')
      ->join('countries','prestige_card_hotels.country_id','countries.id')
      ->orWhere('countries.country_name', 'like', '%' . $countryName . '%')
      ->get();

    $hotelsSeasons = DB::table('countries')->select('low_season','mid_season','high_season','peak_season')
      ->where('country_name', 'like', $countryName)
      ->get();
      //print "<pre>"; print_r($hotelsSeasons);exit;
      if (!$hotelName) {
          //$hotelName = "None";
      }
      if(!empty($hotelName) && empty($countryName)) {
          //$countryName = "None";
      }

      if(empty($hotelList1)) {
        //$hotelName = "None";
      }
//echo $hotelName.$countryName;
      if(!empty($hotelName) && !empty($countryName)) {
        //echo "yes";exit;
          $hotelsPoints = DB::table('prestige_card_hotels')->select('prestige_card_hotels.remarks as remarks', 'hotel_name', 'mode', 'prestige_card_points.hotel_id', 'country_name', 'prestige_card_points.remarks as more_remarks','low_season_points','mid_season_points','high_season_points','peak_season_points','upgrade_points','points','room_type')
      ->join('prestige_card_points','prestige_card_hotels.id','prestige_card_points.hotel_id')
      ->join('countries','prestige_card_hotels.country_id','countries.id')
      ->where('prestige_card_hotels.hotel_name', 'like', '%' . $hotelName . '%')
      ->orderByRaw('prestige_card_hotels.id ASC')
      ->get();

      $hotelsMealPoints = DB::table('prestige_card_hotels')->select('hotel_id','hotel_name','country_name','breakfast_points','lunch_points','dinner_points')
      ->join('prestige_card_meal_points','prestige_card_hotels.id','prestige_card_meal_points.hotel_id')
      ->join('countries','prestige_card_hotels.country_id','countries.id')
      ->where('prestige_card_hotels.hotel_name', 'like', '%' . $hotelName . '%')
      ->orderByRaw('prestige_card_hotels.id ASC')
      ->get();

      $hotelsSeasons = DB::table('prestige_card_hotels')->select('prestige_card_hotels.id as hotel_id','hotel_name','low_season','mid_season','high_season','peak_season')
      ->join('countries','prestige_card_hotels.country_id','countries.id')
      ->where('prestige_card_hotels.hotel_name', 'like', '%' . $hotelName . '%')
      ->orderByRaw('prestige_card_hotels.id ASC')
      ->get();
      } else {
        //echo "no"; exit;
        $hotelName = "None";
        $hotelsPoints = DB::table('prestige_card_hotels')->select('prestige_card_hotels.remarks as remarks', 'hotel_name', 'mode', 'prestige_card_points.hotel_id', 'country_name', 'prestige_card_points.remarks as more_remarks','low_season_points','mid_season_points','high_season_points','peak_season_points','upgrade_points','points','room_type')
      ->join('prestige_card_points','prestige_card_hotels.id','prestige_card_points.hotel_id')
      ->join('countries','prestige_card_hotels.country_id','countries.id')
      ->where('prestige_card_hotels.hotel_name', 'like', '%' . $hotelName . '%')
      ->orWhere('countries.country_name', 'like', '%' . $countryName . '%')
      //->orderBy =Raw('countries.id - prestige_card_hotels.id ASC')
      ->orderByRaw('prestige_card_hotels.id ASC')
      ->get();

      $hotelsMealPoints = DB::table('prestige_card_hotels')->select('hotel_id','hotel_name','country_name','breakfast_points','lunch_points','dinner_points')
      ->join('prestige_card_meal_points','prestige_card_hotels.id','prestige_card_meal_points.hotel_id')
      ->join('countries','prestige_card_hotels.country_id','countries.id')
      ->where('prestige_card_hotels.hotel_name', 'like', '%' . $hotelName . '%')
      ->orWhere('countries.country_name', 'like', '%' . $countryName . '%')
      ->orderByRaw('prestige_card_hotels.id ASC')
      ->get();
      }

      $hotels = array();
      $i = 0;      
      foreach ($hotelsPoints as $hotelsPoint) {
        $hotelId = $hotelsPoint->hotel_id;
        $hotels[$hotelId][0] = $hotelsPoint->hotel_name;
        $hotels[$hotelId][1] = $hotelsPoint->remarks;
        $hotels[$hotelId][2] = $hotelsPoint->country_name;
        foreach ($hotelsPoint as $key => $value) {
          if($key == 'room_type' || $key == 'low_season_points'|| $key == 'mid_season_points'
            || $key == 'high_season_points'|| $key == 'peak_season_points' 
            || $key == 'upgrade_points' || $key == 'points') {
              $hotels[$hotelId][3][$i][] = $value;
          }
        }
        $hotels[$hotelId][4] = $hotelsPoint->mode;
        ++$i;
      }
      foreach ($hotelsMealPoints as $mealsPoint) {
          $hotelId = $mealsPoint->hotel_id;
          foreach ($mealsPoint as $key => $value) {
              if($key == 'breakfast_points' || $key == 'lunch_points'|| $key == 'dinner_points') {
                  $hotels[$hotelId][5][] = $value;
              }
          }
      }

      $countryList = array();
      foreach ($countryList1 as $value) {
        $countryList[] = $value->country_name;
      }
      $hotelList = array();
      foreach ($hotelList1 as $value) {
        $hotelList[] = $value->hotel_name;
      }
      return view('prestige_card_hotels.hotels', compact('hotels','countryList','hotelList','countryName','hotelName','hotelsSeasons'));
}



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        $prestigeCardHotel = new PrestigeCardHotel();
        return view('prestige_card_hotels.create', compact('prestigeCardHotel','countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'hotel_name' => 'required',
            'remarks' => 'required'
        ]);
        $prestigeCardHotel = new PrestigeCardHotel([
            'hotel_name' => $request->get('hotel_name'),
            'mode' => $request->get('mode'),
            'country_id' => $request->get('country_id'),
            'remarks' => $request->get('remarks')
        ]);
        $prestigeCardHotel->save();
        /*if ($request->hasFile('input_img')) {
            if($request->file('input_img')->isValid()) {
                try {
                    $file = $request->file('input_img');
                    $name = time() . '.' . $file->getClientOriginalExtension();
                    $img = Image::make(public_path($request->file('input_img')));
                    $img->resize(25, 25);
                    $img->save(public_path("/uploads/" . $name));
                    echo "file saved...";exit;
                } catch (Illuminate\Filesystem\FileNotFoundException $e) {
                }
            } 
        }*/
        return redirect('/prestige-card-hotels')->with('success', 'Hotel has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function find(Request $request)
    {
        $countryName = $request->get('country');
        $hotelName = $request->get('hotel');
        $countryList1 = DB::table('countries')->select('country_name')->get();
        $hotelList1 = DB::table('prestige_card_hotels')->select('hotel_name')
          ->join('countries','prestige_card_hotels.country_id','countries.id')
          ->orWhere('countries.country_name', 'like', '%' . $countryName . '%')
          ->get();
          $countryList = array();
      foreach ($countryList1 as $value) {
        $countryList[] = $value->country_name;
      }
      $hotelList = array();
      foreach ($hotelList1 as $value) {
        $hotelList[] = $value->hotel_name;
      }
        return view('prestige_card_hotels.find', compact('countryList','hotelList','countryName','hotelName'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $countries = Country::all();
        $prestigeCardHotel = PrestigeCardHotel::find($id);
        return view('prestige_card_hotels.edit', compact('prestigeCardHotel','countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'hotel_name' => 'required',
            'remarks' => 'required'
        ]);
        $prestigeCardHotel = PrestigeCardHotel::find($id);
        $prestigeCardHotel->hotel_name = $request->get('hotel_name');
        $prestigeCardHotel->country_id = $request->get('country_id');
        $prestigeCardHotel->remarks = $request->get('remarks');
        $prestigeCardHotel->mode = $request->get('mode');
        $prestigeCardHotel->save();

        if ($request->hasFile('input_img')) {
            if($request->file('input_img')->isValid()) {
                try {
                    $file = $request->file('input_img');

resources/views/prestige_card_hotels/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Prestige Card Hotel
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('prestige-card-hotels.store') }}">
          @include('prestige_card_hotels.form')
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/prestige_card_hotels/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Prestige Card Hotel
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post"
      enctype="multipart/form-data"
      action="{{ route('prestige-card-hotels.update', $prestigeCardHotel->id) }}">
        @method('PATCH')
        @csrf
        @include('prestige_card_hotels.form')
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/prestige_card_hotels/find-form.blade.php
<style>
  .left {
    text-align:left;
    wwidth:250px;
  }
  
  .right {
    text-align:right;
  }

  .underline {
    border-bottom: solid 2px #777;
  }

  .italics {
    font-style:italic;
  }

  .margin-20 {
    margin-top:20px;
  }

  .border {
    border:solid 1px #999;
  }
</style>
<div class="row margin-20">
  <div class="col-sm-12"> 
  <div class="col-sm-12 left">
    <h2>Find by country or hotel name</h2>
  </div>
    <form method="get" action="{{ URL::to('/') }}/prestige-card-hotels/show">
        <select  class="col-sm-6" class="form-control" 
          onchange="this.form.submit()" name="country">
          <option value="">Select Country</option>
          @foreach ($countryList as $country)
            <option value="{{ $country }}"
             @if($country == $countryName) selected="selected" @endif
            >{{ $country }}</option>
          @endforeach
        </select>
        <select  class="col-sm-6" class="form-control" 
          onchange="this.form.submit()" name="hotel">
          <option value="">Select Hotel</option>
          @foreach ($hotelList as $hotel)
            <option value="{{ $hotel }}"
            @if($hotel == $hotelName) selected="selected" @endif
            >{{ $hotel }}</option>
          @endforeach
        </select>
    </form>
  </div>
</div>

resources/views/prestige_card_hotels/find.blade.php
@extends('layouts.spc-b.inner')

@section('caption')
Serena Prestige Points
@endsection

@section('filename')
background-image: url({{ asset('spc-b') }}/img/header3.jpg);
@endsection

@section('description')
Redeem your accumulated points for a variety of benefits that you deserve.
@endsection

@section('content')
<p>Experience world-class members only Prestige Club programme that grants you access to be part of the Serena loyalty family. As part of our family, experience uniquely personalized authentic travel experiences wherever you stay with us. Whether you are traveling for business or leisure, we are at your service to enhance your stay with our unique rewards that show you how valued you are.</p>
@include('prestige_card_hotels.find-form')
@endsection

resources/views/prestige_card_hotels/form.blade.php
<div class="form-group">
  @csrf
  <label for="name">Hotel Name:</label>
  <input type="text" class="form-control" name="hotel_name" value={{ $prestigeCardHotel->hotel_name }}></input>
</div>
<div class="form-group">
  <label for="name">Remarks:</label>
  <input type="text" class="form-control" name="remarks" value={{ $prestigeCardHotel->remarks }}></input>
</div>
<div class="form-group">
  <label for="mode">Mode:</label>
  <input type="text" class="form-control" name="mode" value={{ $prestigeCardHotel->mode }}></input>
</div>
<div class="form-group">
  <label for="intro">Hotel Country:</label>
  <select class="form-control col-sm-4" name="country_id">
      @foreach($countries as $country)
      <option value="{{$country->id}}" @if($prestigeCardHotel->country_id === $country->id) selected @endif>
        {{ $country->country_name }}
      </option>
      @endforeach
  </select>
  <label for="imageInput">File input</label>
        <input data-preview="#preview" name="input_img" type="file" id="imageInput" />
</div>

resources/views/prestige_card_hotels/hotels.blade.php
@extends('layouts.spc-b.inner')

@section('caption')
Serena Prestige Points
@endsection

@section('filename')
background-image: url({{ asset('spc-b') }}/img/header3.jpg);
@endsection

@section('description')
Redeem your accumulated points for a variety of benefits that you deserve.
@endsection

@section('content')
@include('prestige_card_hotels.find-form')
@if($hotelsSeasons[0]->low_season != "")
<table class="col-sm-8">
      <tr>
          <td class="border-right border-bottom left"><em>Low Season</em></td>
          <td class="left border-bottom">&nbsp;{{ $hotelsSeasons[0]->low_season }}</td>
          <td class="border-right border-bottom left"><em>Mid Season</em></td>
          <td class="left border-bottom">&nbsp;{{ $hotelsSeasons[0]->mid_season }}</td>
      </tr>
      <tr>
          <td class="border-right border-bottom left"><em>High Season</em></td>
          <td class="left border-bottom">&nbsp;{{ $hotelsSeasons[0]->high_season }}</td>
          <td class="border-right border-bottom left"><em>Peak Season</em></td>
          <td class="left border-bottom">&nbsp;{{ $hotelsSeasons[0]->peak_season }}</td>
      </tr>
     </table>
@endif
@foreach ($hotels as $hotel)
  <style>
    .border-right {
      border-right:solid 1px #ccc;
      padding-right:5px;
    }
  </style>
  <div class="col-sm-9 reward-points border">
    <?php if($hotel[4] == 1) { ?>
     <table>
        <tr><th class="left" colspan="6"><h4>{{ $hotel[0] }}, {{ $hotel[2] }}</h4></th></tr>
        <tr>
          <td class="border-right left underline italics">Room Type</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Low Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Mid Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;High Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Peak Season</td>
        </tr>
        @foreach ($hotel[3] as $room)
        <tr>
          <td class="border-right left">{{ $room[6] }}</td>
          <td class="border-right right">{{ $room[0] }}</td>
          <td class="border-right right">{{ $room[1] }}</td>
          <td class="border-right right">{{ $room[2] }}</td>
          <td class="border-right right">{{ $room[3] }}</td>
        </tr>
        @endforeach
        <tr><td class="left border-top" colspan="6">{{ $hotel[1] }}</td></tr>
     </table>
     <?php } elseif ($hotel[4] == 2) { ?>
      <table>
        <tr><th class="left" colspan="6"><h4>{{ $hotel[0] }}, {{ $hotel[2] }}</h4></th></tr>
        <tr>
          <td class="border-right left underline italics">Room Type</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Low Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Mid Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;High Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Peak Season</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Upgrade Points</td>
        </tr>
        @foreach ($hotel[3] as $room)
        <tr>
          <td class="border-right left">{{ $room[6] }}</td>
          <td class="border-right right">{{ $room[0] }}</td>
          <td class="border-right right">{{ $room[1] }}</td>
          <td class="border-right right">{{ $room[2] }}</td>
          <td class="border-right right">{{ $room[3] }}</td>
          <td class="border-right right">{{ $room[4] }}</td>
        </tr>
        @endforeach
        <tr><td class="left border-top" colspan="6">{{ $hotel[1] }}</td></tr>
     </table>
     <?php } elseif ($hotel[4] == 3) { ?>
      <table>
        <tr><th class="left" colspan="6"><h4>{{ $hotel[0] }}, {{ $hotel[2] }}</h4></th></tr>
        <tr>
          <td class="border-right left underline italics">Room Type</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Points</td>
        </tr>
        @foreach ($hotel[3] as $room)
        <tr>
          <td class="border-right left">{{ $room[6] }}</td>
          <td class="border-right right">{{ $room[5] }}</td>
        </tr>
        @endforeach
        <tr><td class="left border-top" colspan="6">{{ $hotel[1] }}</td></tr>
     </table>
     <?php } else { ?>
      <table>
        <tr><th class="left" colspan="6"><h4>{{ $hotel[0] }}, {{ $hotel[2] }}</h4></th></tr>
        <tr>
          <td class="border-right left underline italics">Room Type</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Points</td>
          <td class="border-right right underline italics">&nbsp;&nbsp;Upgrade Points</td>
        </tr>
        @foreach ($hotel[3] as $room)
        <tr>
          <td class="border-right left">{{ $room[6] }}</td>
          <td class="border-right right">{{ $room[5] }}</td>
          <td class="border-right right">{{ $room[4] }}</td>
        </tr>
        @endforeach
        <tr><td class="left border-top" colspan="6">{{ $hotel[1] }}</td></tr>
     </table>
     <?php } ?>
     </div>
     <div class="col-sm-3 reward-points">
     <?php if(!empty($hotel[5])) { ?>
     <table class="col-sm-12">
      <tr><td colspan="2">&nbsp;</td></tr>
      <tr><th colspan="2">Meals Redeem Points</th></tr>
      <tr>
          <td class="border-right border-bottom left">Meal *</td><td class="right border-bottom">&nbsp;Points</td>
      </tr>
      <tr>
          <td class="border-right left">Breakfast</td><td class="right">&nbsp;{{ $hotel[5][0] }}</td>
      </tr>
      <tr>
          <td class="border-right left">Lunch</td><td class="right">&nbsp;{{ $hotel[5][1] }}</td>
      </tr>
      <tr>
          <td class="border-right left">Dinner</td><td class="right">&nbsp;{{ $hotel[5][2] }}</td>
      </tr>
      <tr>
          <td colspan="2" class="border-top left">* Per Person</td>
      </tr>
     </table>
     <?php } ?>
  </div>
@endforeach
</div>
@endsection

resources/views/prestige_card_hotels/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <a href="{{ route('prestige-card-hotels.create')}}" class="btn btn-primary">Add</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Hotel Name</td>
          <td colspan="5">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($prestigeCardHotels as $prestigeCardHotel)
        <tr>
            <td>{{$prestigeCardHotel->id}}</td>
            <td>{{$prestigeCardHotel->hotel_name}}</td>
            <td><a href="{{ route('prestige-card-hotels.edit',$prestigeCardHotel->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('prestige-card-hotels.destroy', $prestigeCardHotel->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
            <td><a href="{{ URL::to('/') }}/prestige-card-points/{{$prestigeCardHotel->id}}/create" class="btn btn-primary">Room Points</a>
            <a href="{{ URL::to('/') }}/prestige-card-points/{{$prestigeCardHotel->id}}" class="btn btn-primary">View</a>
            </td>

            <td><a href="{{ URL::to('/') }}/prestige-card-meal-points/{{$prestigeCardHotel->id}}/create" class="btn btn-primary">Meal Points</a>
            <a href="{{ URL::to('/') }}/prestige-card-meal-points/{{$prestigeCardHotel->id}}" class="btn btn-primary">View</a>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection