routes/web.php
<?php

use App\Tools\MemberRegistration;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('/en/home');
});

//Route::get('/en/home', function () { return view('index');});
Route::get('/en/home', ['uses' =>'HomeController@index']);
Route::get('/en/{slug}', ['uses' =>'ContentController@page']);
Route::get('/display/{key}', ['uses' =>'SuggestionController@display']);
Route::get('/view/{slug}', ['uses' =>'SuggestionController@view']);
Route::get('/member/points', ['uses' =>'MemberController@checkPoints']);
Route::get('/serena-hotels/points', ['uses' =>'PrestigeCardHotelController@find']);

Route::get('/menu-items/{menu_id}/create', ['uses' =>'MenuItemController@create']);
Route::get('/menu-items/{menu_id}', ['uses' =>'MenuItemController@index']);
Route::get('/suggestions/{type_id}/create', ['uses' =>'SuggestionController@create']);
Route::get('/suggestions/{type_id}', ['uses' =>'SuggestionController@index']);
Route::get('/prestige-card-hotels/find', ['uses' =>'PrestigeCardHotelController@find']);	
Route::get('/prestige-card-points/{hotel_id}/create', ['uses' =>'PrestigeCardPointController@create']);
Route::get('/prestige-card-points/{hotel_id}', ['uses' =>'PrestigeCardPointController@index']);
Route::get('/prestige-card-meal-points/{hotel_id}/create', ['uses' =>'PrestigeCardMealPointController@create']);
Route::get('/prestige-card-meal-points/{hotel_id}', ['uses' =>'PrestigeCardMealPointController@index']);

Route::get('/members/enrol', ['uses' =>'MemberController@enrol']);

Route::get('/confirm/success', function () { 
	return redirect('/confirm')->with('success', 'Member has been successfully enrolled');
});
Route::get('/confirm/error', function () { 
	return redirect('/confirm')->with('error', 'Member not enrolled, an error occured!');
});

Route::get('/confirm', function () { return view('members.confirm');});

Route::get('/points2', function () { return view('members.points');});

Route::resource('prestige-card-hotels', 'PrestigeCardHotelController');
Route::resource('prestige-card-points', 'PrestigeCardPointController');
Route::resource('prestige-card-meal-points', 'PrestigeCardMealPointController');
Route::resource('menu-items', 'MenuItemController');
Route::resource('menus', 'MenuController');
Route::resource('suggestions', 'SuggestionController');
Route::resource('suggestion-types', 'SuggestionTypeController');
Route::resource('content-types', 'ContentTypeController');
Route::resource('contents', 'ContentController');
Route::resource('countries', 'CountryController');
Route::resource('members', 'MemberController');
Route::resource('admin/members', 'MemberController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index')->name('admin');

app/Http/Controllers/ContentTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ContentType;

class ContentTypeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $contentTypes = ContentType::all();
        return view('content_types.index', compact('contentTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $contentType = new ContentType();
        return view('content_types.create', compact('contentType'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'content_type_text' => 'required'
        ]);
        $contentType = new ContentType([
        'content_type_text' => $request->get('content_type_text')
        ]);
        $contentType->save();
        return redirect('/content-types')->with('success', 'Content type has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $contentType = ContentType::find($id);
        return view('content_types.edit', compact('contentType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
        'content_type_text' => 'required'
        ]);
        $contentType = ContentType::find($id);
        $contentType->content_type_text = $request->get('content_type_text');
        $contentType->save();
        return redirect('/content-types')->with('success', 'Content type has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/content_types/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Add Content Type
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('content-types.store') }}">
          @include('content_types.form')
          <button type="submit" class="btn btn-primary">Add</button>
      </form>
  </div>
</div>
@endsection

resources/views/content_types/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit content Type
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('content-types.update', $contentType->id) }}">
        @method('PATCH')
        @csrf
        @include('content_types.form')
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/content_types/form.blade.php
<div class="form-group">
  @csrf
  <label for="name">Content Type Text:</label>
  <input type="text" class="form-control" name="content_type_text" value={{ $contentType->content_type_text }}></input>
</div>

resources/views/content_types/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <a href="{{ route('content-types.create')}}" class="btn btn-primary">Add</a>
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Content Type Text</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($contentTypes as $contentType)
        <tr>
            <td>{{$contentType->id}}</td>
            <td>{{$contentType->content_type_text}}</td>
            <td><a href="{{ route('content-types.edit',$contentType->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('content-types.destroy', $contentType->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection